Support symlinks, proper time and translate errors
wiiu-env/libiosuhax pull request #5
Opened 2022-03-30 01:22 UTC by Crementif

It has some duplicate wut structs to extend them, so I'll probably make a pull request to add it to wut (might take a while though). But let me know if there's any issues or things I should look into.

I tried to make everything backwards compatible as much as possible while being sensible. Existing code should still compile (from what I've tested).

I had some issues deciding whether I wanted to return multiple file modes, but it's not really clear whether it's really supported in posix and due to there also being a conversion to DT_REG/DT_DIR etc for directory entries it's probably just better to have no mixing. Also better for compatibility reasons since existing code probably doesn't use bit operators to check them.

Credits to @koolkdev for figuring out the FSStat flags and structs.

2022-03-30 14:45 UTC, Maschell commented on source/iosuhax_devoptab.c
> +static int fs_dev_translate_error(FSStatus error) {
Mixing FS_STATUS and FS_ERROR doesn't really make much sense, see https://github.com/devkitPro/wut/pull/213

2022-03-30 14:48 UTC, Maschell commented on source/iosuhax_devoptab.c
> +        // Turn Wii U's FSStat mode to posix stat
This mapping is done three times in the code, it should/could extracted into a own function like for example: `fs_dev_translate_error`

2022-03-30 14:51 UTC, Maschell commented on include/iosuhax.h
> +typedef enum FSDevMode {
Seems to be identical to [FSMode](https://github.com/devkitPro/wut/blob/master/include/coreinit/filesystem.h#L121) from wut. I would prefer using the existing modes instead of defining a new one (or just do a typedef?)

2022-03-30 14:52 UTC, Maschell commented on source/iosuhax_devoptab.c
> +void FSTimeToCalendarTime(OSTime time, OSCalendarTime *calendarTime);
I would prefer adding this to wut instead of defining it just in this project

2022-03-30 14:53 UTC, Maschell commented on source/iosuhax_devoptab.c
> +    // WHBLogPrintf("[DEBUG] date: %d-%d-%d, time: %d:%d:%d", fileTime.tm_year, fileTime.tm_mon, fileTime.tm_mday, fileTime.tm_hour, fileTime.tm_min, fileTime.tm_sec);
Remove comment

2022-03-30 14:53 UTC, Maschell commented on source/iosuhax_devoptab.c
> +// static int fs_dev_fchmod_r(struct _reent *r, void *fd, mode_t mode) {
Why is this commented out?

2022-03-30 14:56 UTC, Maschell commented
Thanks for the contribution.
1. Please fix the the formatting according to the ,clangformat, can be easily done via docker (`docker run --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -r ./source ./include -i`)
2. I've only done a code review, but didn't test it yet. Beside the parts I have commented it looks reasonable though, great stuff!

2022-03-31 00:13 UTC, Crementif commented on source/iosuhax_devoptab.c
> +void FSTimeToCalendarTime(OSTime time, OSCalendarTime *calendarTime);
Yeah, I plan on doing some pull requests with the changes I've made here regarding the time function and the dev flags. You probably know better if waiting with this PR if waiting for that is a better idea. When writing I was just thinking that it'd probably take a while for that stuff to be in a stable wut release, so I opted for defining it in the .cpp file.

2022-03-31 00:15 UTC, Crementif commented on source/iosuhax_devoptab.c
> +static int fs_dev_translate_error(FSStatus error) {
Added the changes from that PR!

2022-03-31 00:18 UTC, Crementif commented on include/iosuhax.h
> +typedef enum FSDevMode {
Didn't want to include a pretty sizeable header like coreinit/filesystem.h for just the fsmode, but it's probably something that'll be done in the future when the new flags are added to wut so it doesn't really hurt.

2022-03-31 00:22 UTC, Crementif commented on source/iosuhax_devoptab.c
> +// static int fs_dev_fchmod_r(struct _reent *r, void *fd, mode_t mode) {
It does work, but it required tracking the path inside the file handle dir and I think there must be a better solution. I eventually wanna fix some of the unsupported functions in this and wut's SD devoptab, but decided that's better to leave out in this PR.

I've removed all the code related to it for now though.

2022-03-31 00:22 UTC, Crementif commented on source/iosuhax_devoptab.c
> +        // Turn Wii U's FSStat mode to posix stat
Yup, definitely makes sense. Done!

2022-03-31 00:40 UTC, Crementif commented
I've made the changes and also ran the clangformat. Thanks for the quick review.

Let me know if you need any help with the testing. I basically just modified WiiUFTPServer to read out the information, still got a [video](https://streamable.com/q8p2ii) of some of the results while going to the BotW update which has the Movie and Layout movies that are symlinks. [Here's the modified version](https://github.com/wiiu-env/libiosuhax/files/8384977/WiiUFtpServer.zip) if that saves any time that shows the file flags.

I also send it to Laf111 and he tested it more properly and said that the timestamps only appear to be correct for folders that are deeper into the mlc filesystem (usually, the levels after /title, /save). Maybe the directories that also have the quota flag? No clue honestly. Does work on all of the folders on the usb01 filesystem.  It also returns 1980 when it doesn't have a timestamp apparently.

He also mentioned that he still can't faccess a file or use realpath/readlink, which makes sense with the changes I've done. It only gives the correct symlink type back.

2022-04-10 03:33 UTC, Crementif commented
I opened up a PR at WUT to upstream some of the local changes done: https://github.com/devkitPro/wut/pull/215.

2022-04-17 14:22 UTC, Crementif commented
I've removed the code that is now upstreamed to wut's source, so this should be good to merge. Will need a new devkitpro release or to build it from source, so I've also added a disclaimer to the readme.

2022-04-17 15:44 UTC, Maschell commented
Thanks! I updated the Dockerfiles to use the latest wut and will test it (hopefully) later today

2022-04-22 22:43 UTC, Crementif commented
I updated it to now also reflect the permissions, and also fixed the order bug that Gary spotted where chmod was uses as devicedata. Apparently it's always been there? 

Also added lstat support to the devoptab, but the (f)stat both require fixing since they've always been broken.

2022-04-23 11:57 UTC, Maschell requested changes
Just a few more things inside the code

2022-04-23 11:57 UTC, Maschell commented on source/iosuhax_devoptab.c
> +        st->st_blocks  = (st->st_size + st->st_blksize - 1) >> 9;
Where is that 9 coming? This looks like a hardcoded blocksize of 512? 
Is the blocksize **always** 512?

doing `st->st_blocks  = (st->st_size + st->st_blksize - 1) / st->st_blksize;` feels a bit better (even though the st_blksize is hardcoded anyway).

2022-04-23 11:57 UTC, Maschell commented on source/iosuhax_devoptab.c
> +static mode_t fs_dev_translate_mode(FSStat fileStat, bool followLinks, bool isRootDirectory) {
Can you add curly braces to all if/else conditions in this function?

2022-04-23 11:57 UTC, Maschell commented on source/iosuhax_devoptab.c
> +    st->st_blocks  = (st->st_size + st->st_blksize - 1) >> 9;
See the other comment

2022-04-23 11:57 UTC, Maschell commented on source/iosuhax_devoptab.c
> +    st->st_blocks  = (st->st_size + st->st_blksize - 1) >> 9;
see other comment

2022-04-23 11:57 UTC, Maschell commented on source/iosuhax_devoptab.c
> +    st->st_blocks  = (st->st_size + st->st_blksize - 1) >> 9;
^

2022-04-23 13:52 UTC, Crementif commented
Changed everything regarding the feedback. I think the >> 9 is just a faster way to divide by 512, so it was chosen by the previous developer.

2022-04-23 19:11 UTC, Maschell approved these changes

2022-05-13 19:16 UTC, Crementif commented
I added the changes mentioned by GaryOderNights in the discord. It'd be nice for other peeps to get this merged I think :p.

2022-05-15 09:31 UTC, merged